themes = {
    'dark': {
        'THEME_TEXT_LIGHT': '#bbbbbb',
        'THEME_TEXT_DARK': '#686868',
        'THEME_TEXT_ACCENT': '#5996a7',
        'THEME_BG_EXTRALIGHT': '#515658',
        'THEME_BG_LIGHT': '#3c3f41',
        'THEME_BG_MID': '#313335',
        'THEME_BG_DARK': '#2b2b2b',
        'THEME_BG_SELECTED': '#515658',
        'THEME_MENU_SELECTED': '#4b6eaf',
        'THEME_MAIN_BUTTON_LIGHT': '#344963',
        'THEME_MAIN_BUTTON_MID': '#26364a',
        'THEME_MAIN_BUTTON_DARK': '#1b2532',
        'THEME_RED': '#e53935',
        'THEME_YELLOW': '#ffeb3b',
        'THEME_GREEN': '#00a05f',
        'THEME_SIGNAL_OFFSET': '#bbbbbb',
        'THEME_SIGNAL_CURVE': '#64FFDA',
        'THEME_ICON_COLOR': '#DFFF00',
        'THEME_ICON_COLOR_DISABLED': '#686868'
    },
    'light': {
        'THEME_TEXT_LIGHT': '#000000',
        'THEME_TEXT_DARK': '#6e6e6e',
        'THEME_TEXT_ACCENT': '#0032a0',
        'THEME_BG_EXTRALIGHT': '#e3e3e3',
        'THEME_BG_LIGHT': '#ffffff',
        'THEME_BG_MID': '#f0f0f0',
        'THEME_BG_DARK': '#bdbdbd',
        'THEME_BG_SELECTED': '#fafafa',
        'THEME_MENU_SELECTED': '#1a7dc4',
        'THEME_MAIN_BUTTON_LIGHT': '#344963',
        'THEME_MAIN_BUTTON_MID': '#26364a',
        'THEME_MAIN_BUTTON_DARK': '#d4d4d4',
        'THEME_RED': '#ff8c11',
        'THEME_YELLOW': '#ffeb3b',
        'THEME_GREEN': '#00a05f',
        'THEME_SIGNAL_OFFSET': '#bbbbbb',
        'THEME_SIGNAL_CURVE': '#64FFDA',
        'THEME_ICON_COLOR': '#f6412d',
        'THEME_ICON_COLOR_DISABLED': '#686868'
    }
}
